org.tbk.spring.testcontainer.bitcoind:
  enabled: true
  rpcuser: this-is-my-rpc-user99
  rpcpassword: correct_horse_battery_staple_99
  exposed-ports:
    - 28332
    - 28333
    - 28334
    - 28335
  commands:
    # [zeromq]
    # Enable publishing of raw block hex to <address>.
    - '-zmqpubrawblock=tcp://0.0.0.0:28332'
    # Enable publishing of raw transaction hex to <address>.
    - '-zmqpubrawtx=tcp://0.0.0.0:28333'
    # Enable publishing of block hashes to <address>.
    - '-zmqpubhashblock=tcp://0.0.0.0:28334'
    # Enable publishing of transaction hashes to <address>.
    - '-zmqpubhashtx=tcp://0.0.0.0:28335'

# mine blocks every 1 - 10 seconds
org.tbk.spring.testcontainer.bitcoind-regtest-miner:
  enabled: true
  # secret to address: across distance search gym explain fruit sense tiny decrease ribbon day course
  coinbase-reward-address: bcrt1q0lhr8js5rrhjl7hf6e80ns3pgk5tjswgg9um9t
  mine-initial-amount-of-blocks: 3
  next-block-duration:
    min-duration-in-millis: 1000
    max-duration-in-millis: 10000

org.tbk.bitcoin.jsonrpc:
  network: regtest
  rpchost: http://localhost
  rpcport: 18443
  rpcuser: this-is-my-rpc-user99
  rpcpassword: correct_horse_battery_staple_99

org.tbk.bitcoin.zeromq:
  network: regtest
  zmqpubrawblock: tcp://localhost:28332
  zmqpubrawtx: tcp://localhost:28333
  zmqpubhashblock: tcp://localhost:28334
  zmqpubhashtx: tcp://localhost:28335

org.tbk.mqtt.moquette.broker:
  enabled: true

org.tbk.bitcoin.tool.mqtt.server:
  enabled: true
