app.name: tbk-bitcoin-spring-boot-starter-lnd-playground-example-app
app.description: A spring boot bitcoin demo application

spring.application.name: 'tbk-bitcoin-spring-boot-starter-demo'
spring.profiles.active: production
spring.http.log-request-details: false

server.port: 8080
server.use-forward-headers: true
server.compression.enabled: true

server.servlet.session.timeout: 24h # Session timeout. If a duration suffix is not specified, seconds are used.

spring.session.store-type: jdbc # Session store type.
spring.session.jdbc.initialize-schema: never # never: do not initialize the schema - we will do that ourselves.
spring.session.jdbc.table-name: SPRING_SESSION # Name of the database table used to store sessions.

spring.jpa.properties.hibernate.dialect: org.sqlite.hibernate.dialect.SQLiteDialect
spring.jpa.properties.hibernate.jdbc.time_zone: UTC

management.server.port: 9001

# LOGGING
logging.file.path: ./var/log
logging.file.name: application.log
logging.config: classpath:logback.xml
logging.level.org.springframework: INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
#logging.level.web: DEBUG

info.app:
  name: "${app.name}"
  description: "${app.description}"
  java:
    version: "${java.version}"
    runtime:
      version: "${java.runtime.version}"
  user:
    timezone: "${user.timezone}"

management.endpoint.health.show-details: 'always'
management.endpoints.web.exposure.include: '*'
management.info.bitcoinJsonRpc.enabled: true
management.info.lndJsonRpc.enabled: true
management.health.bitcoinJsonRpc.enabled: true
management.health.lndJsonRpc.enabled: true

app:
  # use your own url here (e.g. https://myapp.ngrok.io)
  lnurl-auth-base-url: http://localhost

org.tbk.tor:
  enabled: false  # default is `true`
  autoPublishEnabled: true # default is `true`
  working-directory: 'tor-working-dir' # default is `tor-working-dir`
  startup-timeout: 30s # default is `60s`
