app.name: tbk-bitcoin-spring-boot-starter-lnd-playground-example-app
app.description: A spring boot bitcoin demo application

spring.application.name: 'tbk-bitcoin-spring-boot-starter-demo'
spring.profiles.active: production
spring.http.log-request-details: false

server.port: 8080
server.use-forward-headers: true
server.compression.enabled: true

management.server.port: 9001

# LOGGING
logging.file.path: ./var/log
logging.file.name: application.log
logging.config: classpath:logback.xml
logging.level.org.springframework: INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
#logging.level.web: DEBUG

info.app:
  name: "${app.name}"
  description: "${app.description}"
  java:
    version: "${java.version}"
    runtime:
      version: "${java.runtime.version}"
  user:
    timezone: "${user.timezone}"

management.endpoint.health.show-details: 'always'
management.endpoints.web.exposure.include: '*'
management.info.bitcoinJsonRpc.enabled: true
management.info.lndJsonRpc.enabled: true
management.health.bitcoinJsonRpc.enabled: true
management.health.lndJsonRpc.enabled: true

org.tbk.tor:
  enabled: true  # default is `true`
  autoPublishEnabled: true # default is `true`
  working-directory: 'tor-working-dir' # default is `tor-working-dir`
  startup-timeout: 30s # default is `60s`
