app.name: tbk-bitcoin-spring-boot-starter-demo
app.description: A spring boot bitcoin demo application

spring.application.name: 'tbk-bitcoin-spring-boot-starter-demo'
spring.profiles.active: production
spring.http.log-request-details: false

server.port: 8080
server.use-forward-headers: true
server.compression.enabled: true

management.server.port: 9001

# LOGGING
logging.file.path: ./var/log
logging.file.name: application.log
logging.config: classpath:logback.xml
logging.level.org.springframework: INFO
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
logging.level.org.tbk.bitcoin.regtest: DEBUG

org.tbk.bitcoin.regtest:
  enabled: true
  # mine blocks every 1 - 10 seconds
  miner:
    enabled: true
    coinbase-reward-address: bcrt1q0xtrupsjmqr7u7xz4meufd3a8pt6v553m8nmvz
    mine-initial-amount-of-blocks: 99
    next-block-duration:
      min-duration-in-millis: 1000
      max-duration-in-millis: 10000

org.tbk.bitcoin.jsonrpc:
  network: regtest
  rpchost: http://localhost
  rpcport: 18443
  rpcuser: regtest-rpc-user
  rpcpassword: regtest-rpc-pass

org.tbk.bitcoin.zeromq:
  network: regtest
  zmqpubrawblock: tcp://127.0.0.1:28332
  zmqpubrawtx: tcp://127.0.0.1:28333
  zmqpubhashblock: tcp://127.0.0.1:28334
  zmqpubhashtx: tcp://127.0.0.1:28335

org.tbk.bitcoin.electrum-daemon.jsonrpc:
  enabled: true
  rpchost: http://localhost
  rpcport: 7000
  rpcuser: rpc-user
  rpcpassword: rpc-pwd